<?php
$version = array(
	'stable'=>array(
		'version'=>'3.7.1',
		'codeName'=>'Bock',
		'build'=>'20190128',
		'releaseDate'=>'2019-01-28',
		'downloadLink'=>'https://www.bludit.com/releases/bludit-3-7-1.zip',
		'downloadMirrorLink'=>'',
		'changelogLink'=>'https://github.com/bludit/bludit/releases/tag/3.7.1',
		'github'=>'https://github.com/bludit/bludit/releases/tag/3.7.1',
		'blog'=>'https://blog.bludit.com/bludit-3-7-1'
	),
	'beta'=>array(
		'version'=>'',
		'codeName'=>'',
		'build'=>'',
		'releaseDate'=>'',
		'downloadLink'=>'',
		'downloadMirrorLink'=>'',
		'changelogLink'=>'',
		'github'=>'',
		'blog'=>''
	),
	'alpha'=>array(
		'version'=>'',
		'codeName'=>'',
		'build'=>'',
		'releaseDate'=>'',
		'downloadLink'=>'',
		'downloadMirrorLink'=>'',
		'changelogLink'=>'',
		'github'=>'',
		'blog'=>''
	)
);
if( !defined('BLUDIT')) {
	header("Content-type:application/json");
	exit( json_encode($version) );
}
