<?php
$version = array(
	'stable'=>array(
		'version'=>'3.9.1',
		'codeName'=>'Porter',
		'build'=>'20190530',
		'releaseDate'=>'2019-05-30',
		'downloadLink'=>'https://www.bludit.com/releases/bludit-3-9-1.zip',
		'downloadMirrorLink'=>'',
		'changelogLink'=>'https://github.com/bludit/bludit/releases/tag/3.9.1',
		'github'=>'https://github.com/bludit/bludit/releases/tag/3.9.1',
		'blog'=>'https://blog.bludit.com/bludit-3-9-1'
	),
	'beta'=>array(
		'version'=>'',
		'codeName'=>'',
		'build'=>'',
		'releaseDate'=>'',
		'downloadLink'=>'',
		'downloadMirrorLink'=>'',
		'changelogLink'=>'',
		'github'=>'',
		'blog'=>''
	),
	'alpha'=>array(
		'version'=>'',
		'codeName'=>'',
		'build'=>'',
		'releaseDate'=>'',
		'downloadLink'=>'',
		'downloadMirrorLink'=>'',
		'changelogLink'=>'',
		'github'=>'',
		'blog'=>''
	)
);
if( !defined('BLUDIT')) {
	header("Content-type:application/json");
	exit( json_encode($version) );
}
